<a href="https://colab.research.google.com/github/obi1204/Python-Courses-and-Projects/blob/main/Texas_Crime_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing crime data from Austin, Houston, Fort Worth and Denton
import pandas as pd

denton_crime = pd.read_csv("Denton Crime Data.csv")
fort_worth_crime = pd.read_csv("Fort Worth Crime 2022.csv")
austin_crime = pd.read_csv("Austin Crime 2022.csv")
houston_crime = pd.read_excel("Houston Crime 2022.xlsx")

<ipython-input-3-db7875e0a822>:5: DtypeWarning: Columns (1,10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  fort_worth_crime = pd.read_csv("Fort Worth Crime 2022.csv")
<ipython-input-3-db7875e0a822>:6: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  austin_crime = pd.read_csv("Austin Crime 2022.csv")

In [ ]:
denton_crime

,id,agency,crime,location_name,date/time,public_address
0,1,DENTON PD,Intimidation,Other/Unknown,2019-11-06 00:00,91XX TEASLEY LN DENTON TX
1,2,DENTON PD,Robbery,PARKING/DROP LOT/GARAGE,2019-11-06 00:00,32XX N LOCUST ST DENTON TX
2,3,DENTON PD,Shoplifting,GROCERY/SUPERMARKET,2019-11-06 00:00,26XX W UNIVERSITY DR DENTON TX
3,4,DENTON PD,Swindle/Confidence,Cyberspace,2019-11-06 00:00,7XX FORT WORTH DR DENTON TX
4,5,DENTON PD,All Other Offenses,Residence/Home,2019-11-06 00:01,30XX HOWARD CT DENTON TX
...,...,...,...,...,...,...
41146,41147,DENTON PD,Burglary/B&E,Residence/Home,2023-06-06 02:58,5XX CARDINAL DR DENTON TX
41147,41148,DENTON PD,Simple Assault,Residence/Home,2023-06-06 02:58,5XX CARDINAL DR DENTON TX
41148,41149,DENTON PD,Vandalism,PARKING/DROP LOT/GARAGE,2023-06-06 08:24,14XX CENTRE PLACE DR DENTON TX
41149,41150,DENTON PD,Drug/Narc Violation,PARKING/DROP LOT/GARAGE,2023-06-06 09:53,30XX E UNIVERSITY DR DENTON TX
41150,41151,DENTON PD,Simple Assault,Residence/Home,2023-06-06 10:50,29XX ANYSA LN DENTON TX

In [ ]:
fort_worth_crime

,Case and Offense,Case Number,Reported Date,Nature Of Call,From Date,Offense,Description,Block Address,City,State,Beat,Division,Council District,Attempt Complete,Location Type,Location Description,Location
0,180094593-35A,180094593,10/22/2018,NARCOTIC VIOLATIONS,10/22/2018 06:15:00 PM,35A,HSC 481.115(B) Poss CS PG 1 <1G 35A DRUG/NARCOTIC,700 CALIFORNIA PKWY N WB,FORT WORTH,TX,J13,NaN,NaN,C,13.0,13 HIGHWAY/ROAD/ALLEY,NaN
1,200085517-90Z,200085517,11/03/2020,HARASS,08/12/2020 05:18:00 AM,90Z,PC 42.07(C) Harassment,1300 MARLBOROUGH DR,FORT WORTH,TX,I16,South,8.0,C,20.0,20 RESIDENCE/HOME,"(32.640426597727426, -97.33851074771222)"
2,210012743-240,210012743,02/20/2021,AUTO THEFT,02/20/2021 08:27:59 PM,240,PC 31.03(E)(4)(A)AUTO Theft>$1500<$20K (Auto t...,SANDY LN & EDERVILLE RD,FORT WORTH,TX,H15,East,5.0,C,18.0,18 PARKING LOT/GARAGE,NaN
3,190047946-35A,190047946,06/04/2019,NARCOTIC VIOLATIONS,06/04/2019 01:33:49 AM,35A,HSC 481.117(B) Poss CS PG 3 <28G 35A DRUG/NARC...,OAK GROVE RD / E IH 20 FWY EB,NaN,TX,I17,NaN,NaN,C,13.0,13 HIGHWAY/ROAD/ALLEY,NaN
4,190031427-90D,190031427,04/13/2019,DWI,04/13/2019 02:44:37 AM,90D,PC 49.04 Driving While Intoxicated 90D DRIVING...,WEST FWY SR WB / GREEN OAKS RD,NaN,TX,L11,NaN,NaN,C,13.0,13 HIGHWAY/ROAD/ALLEY,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315228,080089665-90Z,80089665,07/31/2008,CITY ORDIN,07/31/2008 04:44:00 PM,90Z,MISC CITY ORDINANCE Misc City Ordinances,6000 E ROSEDALE ST,FORT WORTH,TX,NaN,NaN,NaN,A,13.0,13 HIGHWAY/ROAD/ALLEY,"(32.72940143032699, -97.22693857343134)"
315229,080089666-240,80089666,07/31/2008,AUTOTHEFT,07/31/2008 03:00:00 PM,240,PC 31.03 - AUTO Auto Theft,8500 EAST FW,FORT WORTH,TX,NaN,NaN,NaN,A,18.0,18 PARKING LOT/GARAGE,"(32.75998313976105, -97.17290554114979)"
315230,080089667-90Z,80089667,07/31/2008,HARASS,07/31/2008 04:00:00 PM,90Z,PC 42.07 Harassment,200 HALLMARK DR W,FORT WORTH,TX,NaN,NaN,NaN,A,20.0,20 RESIDENCE/HOME,"(32.645514865010064, -97.32745649899542)"
315231,080089668-23H,80089668,07/31/2008,THEFT,07/28/2008 09:00:00 PM,23H,PC 31.03 - Others Theft - Others,1000 WHISPER WOODS CIR,FORT WORTH,TX,NaN,NaN,NaN,A,20.0,20 RESIDENCE/HOME,"(32.76456153481421, -97.20437782869296)"
315232,080089669-23F,80089669,07/31/2008,BURG VEHIC,07/27/2008 09:00:00 PM,23F,PC 30.04 Burglary of Vehicle,2800 PECOS ST,FORT WORTH,TX,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
austin_crime

,Incident Number,Highest Offense Description,Highest Offense Code,Family Violence,Occurred Date Time,Occurred Date,Occurred Time,Report Date Time,Report Date,Report Time,...,Census Tract,Clearance Status,Clearance Date,UCR Category,Category Description,X-coordinate,Y-coordinate,Latitude,Longitude,Location
0,202221104,DEPENDENT AND NEGLECTED CHILD,2006,N,01/02/2022 07:56:00 PM,01/02/2022,1956,01/02/2022 07:56:00 PM,01/02/2022,1956,...,415.0,N,01/03/2022,NaN,NaN,0.0,0.0,NaN,NaN,NaN
1,20225000062,THEFT,600,N,01/01/2022 07:00:00 PM,01/01/2022,1900,01/02/2022 12:43:00 AM,01/02/2022,43,...,15.0,NaN,NaN,23H,Theft,3120240.0,10094051.0,30.331726,-97.722305,POINT (-97.72230503 30.33172624)
2,202221365,FAMILY DISTURBANCE,3400,N,01/02/2022 10:28:00 PM,01/02/2022,2228,01/02/2022 10:28:00 PM,01/02/2022,2228,...,24.0,N,01/03/2023,NaN,NaN,3099115.0,10026946.0,30.148609,-97.794104,POINT (-97.79410351 30.14860935)
3,20228000169,BURGLARY OF VEH-NO SUSPECT/FU,601,N,12/26/2021 01:00:00 AM,12/26/2021,100,01/02/2022 03:40:00 PM,01/02/2022,1540,...,347.0,N,01/11/2022,23F,Theft,3068619.0,10051453.0,30.217854,-97.888858,POINT (-97.88885829 30.21785433)
4,202221283,THEFT CATALYTIC CONVERTER,620,N,12/29/2021 05:37:00 AM,12/29/2021,537,01/02/2022 11:28:00 PM,01/02/2022,2328,...,9800.0,N,03/28/2022,23G,Theft,3138851.0,10047302.0,30.202008,-97.666881,POINT (-97.6668813 30.20200809)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87625,20228024566,BURGLARY OF RESIDENCE,500,N,12/30/2022 08:00:00 PM,12/30/2022,2000,12/31/2022 08:25:00 PM,12/31/2022,2025,...,310.0,N,03/02/2023,220,Burglary,3090828.0,10047484.0,30.205583,-97.818846,POINT (-97.81884619 30.20558298)
87626,20223651533,AGG ASSAULT WITH MOTOR VEH,406,N,12/31/2022 11:45:00 PM,12/31/2022,2345,12/31/2022 11:52:00 PM,12/31/2022,2352,...,405.0,N,03/06/2023,13A,Aggravated Assault,3122163.0,10102820.0,30.355707,-97.715557,POINT (-97.71555725 30.35570659)
87627,20225034957,ARSON,800,N,12/31/2022 01:07:00 AM,12/31/2022,107,12/31/2022 01:08:00 AM,12/31/2022,108,...,2.0,N,04/05/2023,NaN,NaN,3115349.0,10091654.0,30.325452,-97.737981,POINT (-97.73798132 30.32545194)
87628,20223651508,POSSESSION OF MARIJUANA,1803,N,12/31/2022 11:26:00 PM,12/31/2022,2326,12/31/2022 11:26:00 PM,12/31/2022,2326,...,11.0,N,04/06/2023,NaN,NaN,3115586.0,10070497.0,30.267279,-97.738794,POINT (-97.73879424 30.26727938)
87629,20223650202,CRASH/FAIL STOP AND RENDER AID,3604,N,12/31/2022 02:46:00 AM,12/31/2022,246,12/31/2022 02:46:00 AM,12/31/2022,246,...,431.0,N,05/03/2023,NaN,NaN,3129166.0,10104694.0,30.360403,-97.693219,POINT (-97.6932192 30.36040289)

In [ ]:
houston_crime

,Incident,RMSOccurrenceDate,RMSOccurrenceHour,NIBRSClass,NIBRSDescription,OffenseCount,Beat,Premise,StreetNo,StreetName,StreetType,Suffix,City,ZIPCode,MapLongitude,MapLatitude
0,10322,2022-01-01,0,90C,Disorderly conduct,1,3B10,"Residence, Home (Includes Apartment)",5500,ANTOINE,DR,NaN,HOUSTON,77091,-95.473227,29.844355
1,10322,2022-01-01,0,520,Weapon law violations,1,3B10,"Residence, Home (Includes Apartment)",5500,ANTOINE,DR,NaN,HOUSTON,77091,-95.473227,29.844355
2,11622,2022-01-01,0,290,"Destruction, damage, vandalism",1,8C20,"Highway, Road, Street, Alley",7100,LEY,RD,NaN,HOUSTON,77028,-95.302010,29.831370
3,15122,2022-01-01,0,290,"Destruction, damage, vandalism",1,11H10,"Residence, Home (Includes Apartment)",6540,AVENUE J,NaN,NaN,HOUSTON,77011,-95.308258,29.744464
4,15122,2022-01-01,0,520,Weapon law violations,1,11H10,"Residence, Home (Includes Apartment)",6540,AVENUE J,NaN,NaN,HOUSTON,77011,-95.308258,29.744464
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249907,176645722,2022-12-31,23,90D,Driving under the influence,1,1A20,"Highway, Road, Street, Alley",1602,VAN BUREN,NaN,NaN,HOUSTON,77006,-95.393723,29.753197
249908,176647422,2022-12-31,23,520,Weapon law violations,1,14D10,"Highway, Road, Street, Alley",7122,ENGLAND,ST,NaN,HOUSTON,77021,-95.359182,29.686532
249909,176649422,2022-12-31,23,90D,Driving under the influence,1,2A50,"Highway, Road, Street, Alley",1300,PARKER,ST,NaN,HOUSTON,77007,-95.408386,29.772879
249910,176649422,2022-12-31,23,90Z,All other offenses,1,2A50,"Highway, Road, Street, Alley",1300,PARKER,ST,NaN,HOUSTON,77007,-95.408386,29.772879
249911,176651222,2022-12-31,23,09A,"Murder, non-negligent",1,17E10,"Parking Lot, Garage",6501,CHIMNEY ROCK,RD,NaN,HOUSTON,77081,-95.476329,29.710020

In [ ]:
#adding city column to Austin table
austin_crime['City'] = 'AUSTIN'
austin_crime

,Incident Number,Highest Offense Description,Highest Offense Code,Family Violence,Occurred Date Time,Occurred Date,Occurred Time,Report Date Time,Report Date,Report Time,...,Clearance Status,Clearance Date,UCR Category,Category Description,X-coordinate,Y-coordinate,Latitude,Longitude,Location,City
0,202221104,DEPENDENT AND NEGLECTED CHILD,2006,N,01/02/2022 07:56:00 PM,01/02/2022,1956,01/02/2022 07:56:00 PM,01/02/2022,1956,...,N,01/03/2022,NaN,NaN,0.0,0.0,NaN,NaN,NaN,AUSTIN
1,20225000062,THEFT,600,N,01/01/2022 07:00:00 PM,01/01/2022,1900,01/02/2022 12:43:00 AM,01/02/2022,43,...,NaN,NaN,23H,Theft,3120240.0,10094051.0,30.331726,-97.722305,POINT (-97.72230503 30.33172624),AUSTIN
2,202221365,FAMILY DISTURBANCE,3400,N,01/02/2022 10:28:00 PM,01/02/2022,2228,01/02/2022 10:28:00 PM,01/02/2022,2228,...,N,01/03/2023,NaN,NaN,3099115.0,10026946.0,30.148609,-97.794104,POINT (-97.79410351 30.14860935),AUSTIN
3,20228000169,BURGLARY OF VEH-NO SUSPECT/FU,601,N,12/26/2021 01:00:00 AM,12/26/2021,100,01/02/2022 03:40:00 PM,01/02/2022,1540,...,N,01/11/2022,23F,Theft,3068619.0,10051453.0,30.217854,-97.888858,POINT (-97.88885829 30.21785433),AUSTIN
4,202221283,THEFT CATALYTIC CONVERTER,620,N,12/29/2021 05:37:00 AM,12/29/2021,537,01/02/2022 11:28:00 PM,01/02/2022,2328,...,N,03/28/2022,23G,Theft,3138851.0,10047302.0,30.202008,-97.666881,POINT (-97.6668813 30.20200809),AUSTIN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87625,20228024566,BURGLARY OF RESIDENCE,500,N,12/30/2022 08:00:00 PM,12/30/2022,2000,12/31/2022 08:25:00 PM,12/31/2022,2025,...,N,03/02/2023,220,Burglary,3090828.0,10047484.0,30.205583,-97.818846,POINT (-97.81884619 30.20558298),AUSTIN
87626,20223651533,AGG ASSAULT WITH MOTOR VEH,406,N,12/31/2022 11:45:00 PM,12/31/2022,2345,12/31/2022 11:52:00 PM,12/31/2022,2352,...,N,03/06/2023,13A,Aggravated Assault,3122163.0,10102820.0,30.355707,-97.715557,POINT (-97.71555725 30.35570659),AUSTIN
87627,20225034957,ARSON,800,N,12/31/2022 01:07:00 AM,12/31/2022,107,12/31/2022 01:08:00 AM,12/31/2022,108,...,N,04/05/2023,NaN,NaN,3115349.0,10091654.0,30.325452,-97.737981,POINT (-97.73798132 30.32545194),AUSTIN
87628,20223651508,POSSESSION OF MARIJUANA,1803,N,12/31/2022 11:26:00 PM,12/31/2022,2326,12/31/2022 11:26:00 PM,12/31/2022,2326,...,N,04/06/2023,NaN,NaN,3115586.0,10070497.0,30.267279,-97.738794,POINT (-97.73879424 30.26727938),AUSTIN
87629,20223650202,CRASH/FAIL STOP AND RENDER AID,3604,N,12/31/2022 02:46:00 AM,12/31/2022,246,12/31/2022 02:46:00 AM,12/31/2022,246,...,N,05/03/2023,NaN,NaN,3129166.0,10104694.0,30.360403,-97.693219,POINT (-97.6932192 30.36040289),AUSTIN

In [ ]:
#removing unnecessary columns so tables will match
updated1_austin = austin_crime.drop(columns = ['Incident Number', 'Highest Offense Code', 'Family Violence', 'Occurred Date Time', 'Occurred Time', 'Report Date Time', 'Report Date', 'Report Time', 'Address', 'Council District', 'APD Sector', 'APD District', 'PRA', 'Census Tract', 'Clearance Status', 'Clearance Date', 'UCR Category', 'Category Description', 'X-coordinate', 'Y-coordinate', 'Latitude', 'Longitude', 'Location'])
updated1_austin

,Highest Offense Description,Occurred Date,Location Type,Zip Code,City
0,DEPENDENT AND NEGLECTED CHILD,01/02/2022,PARKING /DROP LOT/ GARAGE,78753.0,AUSTIN
1,THEFT,01/01/2022,SERVICE/ GAS STATION,78752.0,AUSTIN
2,FAMILY DISTURBANCE,01/02/2022,RESIDENCE / HOME,78748.0,AUSTIN
3,BURGLARY OF VEH-NO SUSPECT/FU,12/26/2021,RESIDENCE / HOME,78749.0,AUSTIN
4,THEFT CATALYTIC CONVERTER,12/29/2021,PARKING /DROP LOT/ GARAGE,78719.0,AUSTIN
...,...,...,...,...,...
87625,BURGLARY OF RESIDENCE,12/30/2022,RESIDENCE / HOME,78745.0,AUSTIN
87626,AGG ASSAULT WITH MOTOR VEH,12/31/2022,HWY / ROAD / ALLEY/ STREET/ SIDEWALK,78758.0,AUSTIN
87627,ARSON,12/31/2022,PARKING /DROP LOT/ GARAGE,78756.0,AUSTIN
87628,POSSESSION OF MARIJUANA,12/31/2022,HWY / ROAD / ALLEY/ STREET/ SIDEWALK,78701.0,AUSTIN
87629,CRASH/FAIL STOP AND RENDER AID,12/31/2022,HWY / ROAD / ALLEY/ STREET/ SIDEWALK,78753.0,AUSTIN

In [ ]:
updated1_houston = houston_crime.drop(columns = ['Incident', 'RMSOccurrenceHour', 'NIBRSClass', 'OffenseCount', 'Beat', 'StreetNo', 'StreetName', 'StreetType','Suffix', 'MapLongitude', 'MapLatitude'])
updated1_houston

,RMSOccurrenceDate,NIBRSDescription,Premise,City,ZIPCode
0,2022-01-01,Disorderly conduct,"Residence, Home (Includes Apartment)",HOUSTON,77091
1,2022-01-01,Weapon law violations,"Residence, Home (Includes Apartment)",HOUSTON,77091
2,2022-01-01,"Destruction, damage, vandalism","Highway, Road, Street, Alley",HOUSTON,77028
3,2022-01-01,"Destruction, damage, vandalism","Residence, Home (Includes Apartment)",HOUSTON,77011
4,2022-01-01,Weapon law violations,"Residence, Home (Includes Apartment)",HOUSTON,77011
...,...,...,...,...,...
249907,2022-12-31,Driving under the influence,"Highway, Road, Street, Alley",HOUSTON,77006
249908,2022-12-31,Weapon law violations,"Highway, Road, Street, Alley",HOUSTON,77021
249909,2022-12-31,Driving under the influence,"Highway, Road, Street, Alley",HOUSTON,77007
249910,2022-12-31,All other offenses,"Highway, Road, Street, Alley",HOUSTON,77007
249911,2022-12-31,"Murder, non-negligent","Parking Lot, Garage",HOUSTON,77081

In [ ]:
denton_crime

,id,agency,crime,location_name,date/time,public_address
0,1,DENTON PD,Intimidation,Other/Unknown,2019-11-06 00:00,91XX TEASLEY LN DENTON TX
1,2,DENTON PD,Robbery,PARKING/DROP LOT/GARAGE,2019-11-06 00:00,32XX N LOCUST ST DENTON TX
2,3,DENTON PD,Shoplifting,GROCERY/SUPERMARKET,2019-11-06 00:00,26XX W UNIVERSITY DR DENTON TX
3,4,DENTON PD,Swindle/Confidence,Cyberspace,2019-11-06 00:00,7XX FORT WORTH DR DENTON TX
4,5,DENTON PD,All Other Offenses,Residence/Home,2019-11-06 00:01,30XX HOWARD CT DENTON TX
...,...,...,...,...,...,...
41146,41147,DENTON PD,Burglary/B&E,Residence/Home,2023-06-06 02:58,5XX CARDINAL DR DENTON TX
41147,41148,DENTON PD,Simple Assault,Residence/Home,2023-06-06 02:58,5XX CARDINAL DR DENTON TX
41148,41149,DENTON PD,Vandalism,PARKING/DROP LOT/GARAGE,2023-06-06 08:24,14XX CENTRE PLACE DR DENTON TX
41149,41150,DENTON PD,Drug/Narc Violation,PARKING/DROP LOT/GARAGE,2023-06-06 09:53,30XX E UNIVERSITY DR DENTON TX
41150,41151,DENTON PD,Simple Assault,Residence/Home,2023-06-06 10:50,29XX ANYSA LN DENTON TX

In [ ]:
updated1_denton = denton_crime.drop(columns = ["id", 'agency', 'public_address'])
updated1_denton

                     crime            location_name         date/time
0             Intimidation            Other/Unknown  2019-11-06 00:00
1                  Robbery  PARKING/DROP LOT/GARAGE  2019-11-06 00:00
2              Shoplifting      GROCERY/SUPERMARKET  2019-11-06 00:00
3       Swindle/Confidence               Cyberspace  2019-11-06 00:00
4       All Other Offenses           Residence/Home  2019-11-06 00:01
...                    ...                      ...               ...
41146         Burglary/B&E           Residence/Home  2023-06-06 02:58
41147       Simple Assault           Residence/Home  2023-06-06 02:58
41148            Vandalism  PARKING/DROP LOT/GARAGE  2023-06-06 08:24
41149  Drug/Narc Violation  PARKING/DROP LOT/GARAGE  2023-06-06 09:53
41150       Simple Assault           Residence/Home  2023-06-06 10:50

[41151 rows x 3 columns]

In [ ]:
updated1_denton['City'] = 'DENTON'
updated1_denton

                     crime            location_name         date/time    City
0             Intimidation            Other/Unknown  2019-11-06 00:00  DENTON
1                  Robbery  PARKING/DROP LOT/GARAGE  2019-11-06 00:00  DENTON
2              Shoplifting      GROCERY/SUPERMARKET  2019-11-06 00:00  DENTON
3       Swindle/Confidence               Cyberspace  2019-11-06 00:00  DENTON
4       All Other Offenses           Residence/Home  2019-11-06 00:01  DENTON
...                    ...                      ...               ...     ...
41146         Burglary/B&E           Residence/Home  2023-06-06 02:58  DENTON
41147       Simple Assault           Residence/Home  2023-06-06 02:58  DENTON
41148            Vandalism  PARKING/DROP LOT/GARAGE  2023-06-06 08:24  DENTON
41149  Drug/Narc Violation  PARKING/DROP LOT/GARAGE  2023-06-06 09:53  DENTON
41150       Simple Assault           Residence/Home  2023-06-06 10:50  DENTON

[41151 rows x 4 columns]

In [ ]:
fort_worth_crime

,Case and Offense,Case Number,Reported Date,Nature Of Call,From Date,Offense,Description,Block Address,City,State,Beat,Division,Council District,Attempt Complete,Location Type,Location Description,Location
0,180094593-35A,180094593,10/22/2018,NARCOTIC VIOLATIONS,10/22/2018 06:15:00 PM,35A,HSC 481.115(B) Poss CS PG 1 <1G 35A DRUG/NARCOTIC,700 CALIFORNIA PKWY N WB,FORT WORTH,TX,J13,NaN,NaN,C,13.0,13 HIGHWAY/ROAD/ALLEY,NaN
1,200085517-90Z,200085517,11/03/2020,HARASS,08/12/2020 05:18:00 AM,90Z,PC 42.07(C) Harassment,1300 MARLBOROUGH DR,FORT WORTH,TX,I16,South,8.0,C,20.0,20 RESIDENCE/HOME,"(32.640426597727426, -97.33851074771222)"
2,210012743-240,210012743,02/20/2021,AUTO THEFT,02/20/2021 08:27:59 PM,240,PC 31.03(E)(4)(A)AUTO Theft>$1500<$20K (Auto t...,SANDY LN & EDERVILLE RD,FORT WORTH,TX,H15,East,5.0,C,18.0,18 PARKING LOT/GARAGE,NaN
3,190047946-35A,190047946,06/04/2019,NARCOTIC VIOLATIONS,06/04/2019 01:33:49 AM,35A,HSC 481.117(B) Poss CS PG 3 <28G 35A DRUG/NARC...,OAK GROVE RD / E IH 20 FWY EB,NaN,TX,I17,NaN,NaN,C,13.0,13 HIGHWAY/ROAD/ALLEY,NaN
4,190031427-90D,190031427,04/13/2019,DWI,04/13/2019 02:44:37 AM,90D,PC 49.04 Driving While Intoxicated 90D DRIVING...,WEST FWY SR WB / GREEN OAKS RD,NaN,TX,L11,NaN,NaN,C,13.0,13 HIGHWAY/ROAD/ALLEY,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315228,080089665-90Z,80089665,07/31/2008,CITY ORDIN,07/31/2008 04:44:00 PM,90Z,MISC CITY ORDINANCE Misc City Ordinances,6000 E ROSEDALE ST,FORT WORTH,TX,NaN,NaN,NaN,A,13.0,13 HIGHWAY/ROAD/ALLEY,"(32.72940143032699, -97.22693857343134)"
315229,080089666-240,80089666,07/31/2008,AUTOTHEFT,07/31/2008 03:00:00 PM,240,PC 31.03 - AUTO Auto Theft,8500 EAST FW,FORT WORTH,TX,NaN,NaN,NaN,A,18.0,18 PARKING LOT/GARAGE,"(32.75998313976105, -97.17290554114979)"
315230,080089667-90Z,80089667,07/31/2008,HARASS,07/31/2008 04:00:00 PM,90Z,PC 42.07 Harassment,200 HALLMARK DR W,FORT WORTH,TX,NaN,NaN,NaN,A,20.0,20 RESIDENCE/HOME,"(32.645514865010064, -97.32745649899542)"
315231,080089668-23H,80089668,07/31/2008,THEFT,07/28/2008 09:00:00 PM,23H,PC 31.03 - Others Theft - Others,1000 WHISPER WOODS CIR,FORT WORTH,TX,NaN,NaN,NaN,A,20.0,20 RESIDENCE/HOME,"(32.76456153481421, -97.20437782869296)"
315232,080089669-23F,80089669,07/31/2008,BURG VEHIC,07/27/2008 09:00:00 PM,23F,PC 30.04 Burglary of Vehicle,2800 PECOS ST,FORT WORTH,TX,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
updated1_fortworth = fort_worth_crime.drop(columns = ['Case and Offense', 'Case Number', 'Offense', 'Block Address', 'State', 'Beat', 'Council District', 'Attempt Complete', 'Location Type'])
updated1_fortworth

,Reported Date,Nature Of Call,From Date,Description,City,Division,Location Description,Location
0,10/22/2018,NARCOTIC VIOLATIONS,10/22/2018 06:15:00 PM,HSC 481.115(B) Poss CS PG 1 <1G 35A DRUG/NARCOTIC,FORT WORTH,NaN,13 HIGHWAY/ROAD/ALLEY,NaN
1,11/03/2020,HARASS,08/12/2020 05:18:00 AM,PC 42.07(C) Harassment,FORT WORTH,South,20 RESIDENCE/HOME,"(32.640426597727426, -97.33851074771222)"
2,02/20/2021,AUTO THEFT,02/20/2021 08:27:59 PM,PC 31.03(E)(4)(A)AUTO Theft>$1500<$20K (Auto t...,FORT WORTH,East,18 PARKING LOT/GARAGE,NaN
3,06/04/2019,NARCOTIC VIOLATIONS,06/04/2019 01:33:49 AM,HSC 481.117(B) Poss CS PG 3 <28G 35A DRUG/NARC...,NaN,NaN,13 HIGHWAY/ROAD/ALLEY,NaN
4,04/13/2019,DWI,04/13/2019 02:44:37 AM,PC 49.04 Driving While Intoxicated 90D DRIVING...,NaN,NaN,13 HIGHWAY/ROAD/ALLEY,NaN
...,...,...,...,...,...,...,...,...
315228,07/31/2008,CITY ORDIN,07/31/2008 04:44:00 PM,MISC CITY ORDINANCE Misc City Ordinances,FORT WORTH,NaN,13 HIGHWAY/ROAD/ALLEY,"(32.72940143032699, -97.22693857343134)"
315229,07/31/2008,AUTOTHEFT,07/31/2008 03:00:00 PM,PC 31.03 - AUTO Auto Theft,FORT WORTH,NaN,18 PARKING LOT/GARAGE,"(32.75998313976105, -97.17290554114979)"
315230,07/31/2008,HARASS,07/31/2008 04:00:00 PM,PC 42.07 Harassment,FORT WORTH,NaN,20 RESIDENCE/HOME,"(32.645514865010064, -97.32745649899542)"
315231,07/31/2008,THEFT,07/28/2008 09:00:00 PM,PC 31.03 - Others Theft - Others,FORT WORTH,NaN,20 RESIDENCE/HOME,"(32.76456153481421, -97.20437782869296)"
315232,07/31/2008,BURG VEHIC,07/27/2008 09:00:00 PM,PC 30.04 Burglary of Vehicle,FORT WORTH,NaN,NaN,NaN

In [ ]:
updated1_austin

,Highest Offense Description,Occurred Date,Location Type,Zip Code,City
0,DEPENDENT AND NEGLECTED CHILD,01/02/2022,PARKING /DROP LOT/ GARAGE,78753.0,AUSTIN
1,THEFT,01/01/2022,SERVICE/ GAS STATION,78752.0,AUSTIN
2,FAMILY DISTURBANCE,01/02/2022,RESIDENCE / HOME,78748.0,AUSTIN
3,BURGLARY OF VEH-NO SUSPECT/FU,12/26/2021,RESIDENCE / HOME,78749.0,AUSTIN
4,THEFT CATALYTIC CONVERTER,12/29/2021,PARKING /DROP LOT/ GARAGE,78719.0,AUSTIN
...,...,...,...,...,...
87625,BURGLARY OF RESIDENCE,12/30/2022,RESIDENCE / HOME,78745.0,AUSTIN
87626,AGG ASSAULT WITH MOTOR VEH,12/31/2022,HWY / ROAD / ALLEY/ STREET/ SIDEWALK,78758.0,AUSTIN
87627,ARSON,12/31/2022,PARKING /DROP LOT/ GARAGE,78756.0,AUSTIN
87628,POSSESSION OF MARIJUANA,12/31/2022,HWY / ROAD / ALLEY/ STREET/ SIDEWALK,78701.0,AUSTIN
87629,CRASH/FAIL STOP AND RENDER AID,12/31/2022,HWY / ROAD / ALLEY/ STREET/ SIDEWALK,78753.0,AUSTIN

In [ ]:
updated1_austin.drop(columns = ["Zip Code"])

,Highest Offense Description,Occurred Date,Location Type,City
0,DEPENDENT AND NEGLECTED CHILD,01/02/2022,PARKING /DROP LOT/ GARAGE,AUSTIN
1,THEFT,01/01/2022,SERVICE/ GAS STATION,AUSTIN
2,FAMILY DISTURBANCE,01/02/2022,RESIDENCE / HOME,AUSTIN
3,BURGLARY OF VEH-NO SUSPECT/FU,12/26/2021,RESIDENCE / HOME,AUSTIN
4,THEFT CATALYTIC CONVERTER,12/29/2021,PARKING /DROP LOT/ GARAGE,AUSTIN
...,...,...,...,...
87625,BURGLARY OF RESIDENCE,12/30/2022,RESIDENCE / HOME,AUSTIN
87626,AGG ASSAULT WITH MOTOR VEH,12/31/2022,HWY / ROAD / ALLEY/ STREET/ SIDEWALK,AUSTIN
87627,ARSON,12/31/2022,PARKING /DROP LOT/ GARAGE,AUSTIN
87628,POSSESSION OF MARIJUANA,12/31/2022,HWY / ROAD / ALLEY/ STREET/ SIDEWALK,AUSTIN
87629,CRASH/FAIL STOP AND RENDER AID,12/31/2022,HWY / ROAD / ALLEY/ STREET/ SIDEWALK,AUSTIN

In [ ]:
drop_hou = updated1_houston.drop(columns = ["ZIPCode"])

In [ ]:
new_columns = ['Occurred Date', 'Highest Offense Description', 'Location Type', 'City']
updated1_austin = updated1_austin[new_columns]
updated1_austin

,Occurred Date,Highest Offense Description,Location Type,City
0,01/02/2022,DEPENDENT AND NEGLECTED CHILD,PARKING /DROP LOT/ GARAGE,AUSTIN
1,01/01/2022,THEFT,SERVICE/ GAS STATION,AUSTIN
2,01/02/2022,FAMILY DISTURBANCE,RESIDENCE / HOME,AUSTIN
3,12/26/2021,BURGLARY OF VEH-NO SUSPECT/FU,RESIDENCE / HOME,AUSTIN
4,12/29/2021,THEFT CATALYTIC CONVERTER,PARKING /DROP LOT/ GARAGE,AUSTIN
...,...,...,...,...
87625,12/30/2022,BURGLARY OF RESIDENCE,RESIDENCE / HOME,AUSTIN
87626,12/31/2022,AGG ASSAULT WITH MOTOR VEH,HWY / ROAD / ALLEY/ STREET/ SIDEWALK,AUSTIN
87627,12/31/2022,ARSON,PARKING /DROP LOT/ GARAGE,AUSTIN
87628,12/31/2022,POSSESSION OF MARIJUANA,HWY / ROAD / ALLEY/ STREET/ SIDEWALK,AUSTIN
87629,12/31/2022,CRASH/FAIL STOP AND RENDER AID,HWY / ROAD / ALLEY/ STREET/ SIDEWALK,AUSTIN

In [ ]:
#renaming colums
final1 = updated1_austin.rename(columns = {'Occurred Date': 'Date_of_Occurrence', 'Highest Offense Description':'Offense_Description', 'Location Type': 'Location_Type', 'City':'City'})
final2 = drop_hou.rename(columns = {'RMSOccurrenceDate': 'Date_of_Occurrence', 'NIBRSDescription':'Offense_Description', 'Premise': 'Location_Type', 'City':'City'})

In [ ]:
final2

,Date_of_Occurrence,Offense_Description,Location_Type,City
0,2022-01-01,Disorderly conduct,"Residence, Home (Includes Apartment)",HOUSTON
1,2022-01-01,Weapon law violations,"Residence, Home (Includes Apartment)",HOUSTON
2,2022-01-01,"Destruction, damage, vandalism","Highway, Road, Street, Alley",HOUSTON
3,2022-01-01,"Destruction, damage, vandalism","Residence, Home (Includes Apartment)",HOUSTON
4,2022-01-01,Weapon law violations,"Residence, Home (Includes Apartment)",HOUSTON
...,...,...,...,...
249907,2022-12-31,Driving under the influence,"Highway, Road, Street, Alley",HOUSTON
249908,2022-12-31,Weapon law violations,"Highway, Road, Street, Alley",HOUSTON
249909,2022-12-31,Driving under the influence,"Highway, Road, Street, Alley",HOUSTON
249910,2022-12-31,All other offenses,"Highway, Road, Street, Alley",HOUSTON
249911,2022-12-31,"Murder, non-negligent","Parking Lot, Garage",HOUSTON

In [ ]:
final1

,Date_of_Occurrence,Offense_Description,Location_Type,City
0,01/02/2022,DEPENDENT AND NEGLECTED CHILD,PARKING /DROP LOT/ GARAGE,AUSTIN
1,01/01/2022,THEFT,SERVICE/ GAS STATION,AUSTIN
2,01/02/2022,FAMILY DISTURBANCE,RESIDENCE / HOME,AUSTIN
3,12/26/2021,BURGLARY OF VEH-NO SUSPECT/FU,RESIDENCE / HOME,AUSTIN
4,12/29/2021,THEFT CATALYTIC CONVERTER,PARKING /DROP LOT/ GARAGE,AUSTIN
...,...,...,...,...
87625,12/30/2022,BURGLARY OF RESIDENCE,RESIDENCE / HOME,AUSTIN
87626,12/31/2022,AGG ASSAULT WITH MOTOR VEH,HWY / ROAD / ALLEY/ STREET/ SIDEWALK,AUSTIN
87627,12/31/2022,ARSON,PARKING /DROP LOT/ GARAGE,AUSTIN
87628,12/31/2022,POSSESSION OF MARIJUANA,HWY / ROAD / ALLEY/ STREET/ SIDEWALK,AUSTIN
87629,12/31/2022,CRASH/FAIL STOP AND RENDER AID,HWY / ROAD / ALLEY/ STREET/ SIDEWALK,AUSTIN

In [ ]:
#reseting indexes before merge
final1.reset_index(drop=True, inplace=True)
final2.reset_index(drop=True, inplace=True)

In [ ]:
#merging tables
merge_austin_houston = pd.concat([final2, final1])

In [ ]:
merge_austin_houston

,Date_of_Occurrence,Offense_Description,Location_Type,City
0,2022-01-01 00:00:00,Disorderly conduct,"Residence, Home (Includes Apartment)",HOUSTON
1,2022-01-01 00:00:00,Weapon law violations,"Residence, Home (Includes Apartment)",HOUSTON
2,2022-01-01 00:00:00,"Destruction, damage, vandalism","Highway, Road, Street, Alley",HOUSTON
3,2022-01-01 00:00:00,"Destruction, damage, vandalism","Residence, Home (Includes Apartment)",HOUSTON
4,2022-01-01 00:00:00,Weapon law violations,"Residence, Home (Includes Apartment)",HOUSTON
...,...,...,...,...
87625,12/30/2022,BURGLARY OF RESIDENCE,RESIDENCE / HOME,AUSTIN
87626,12/31/2022,AGG ASSAULT WITH MOTOR VEH,HWY / ROAD / ALLEY/ STREET/ SIDEWALK,AUSTIN
87627,12/31/2022,ARSON,PARKING /DROP LOT/ GARAGE,AUSTIN
87628,12/31/2022,POSSESSION OF MARIJUANA,HWY / ROAD / ALLEY/ STREET/ SIDEWALK,AUSTIN
87629,12/31/2022,CRASH/FAIL STOP AND RENDER AID,HWY / ROAD / ALLEY/ STREET/ SIDEWALK,AUSTIN

In [ ]:
updated1_denton

                     crime            location_name         date/time    City
0             Intimidation            Other/Unknown  2019-11-06 00:00  DENTON
1                  Robbery  PARKING/DROP LOT/GARAGE  2019-11-06 00:00  DENTON
2              Shoplifting      GROCERY/SUPERMARKET  2019-11-06 00:00  DENTON
3       Swindle/Confidence               Cyberspace  2019-11-06 00:00  DENTON
4       All Other Offenses           Residence/Home  2019-11-06 00:01  DENTON
...                    ...                      ...               ...     ...
41146         Burglary/B&E           Residence/Home  2023-06-06 02:58  DENTON
41147       Simple Assault           Residence/Home  2023-06-06 02:58  DENTON
41148            Vandalism  PARKING/DROP LOT/GARAGE  2023-06-06 08:24  DENTON
41149  Drug/Narc Violation  PARKING/DROP LOT/GARAGE  2023-06-06 09:53  DENTON
41150       Simple Assault           Residence/Home  2023-06-06 10:50  DENTON

[41151 rows x 4 columns]

In [ ]:
final3 = updated1_denton.rename(columns = {'date/time': 'Date_of_Occurrence', 'location_name': 'Location_Type', 'crime' : 'Offense_Description'})
final3

       Offense_Description            Location_Type Date_of_Occurrence    City
0             Intimidation            Other/Unknown   2019-11-06 00:00  DENTON
1                  Robbery  PARKING/DROP LOT/GARAGE   2019-11-06 00:00  DENTON
2              Shoplifting      GROCERY/SUPERMARKET   2019-11-06 00:00  DENTON
3       Swindle/Confidence               Cyberspace   2019-11-06 00:00  DENTON
4       All Other Offenses           Residence/Home   2019-11-06 00:01  DENTON
...                    ...                      ...                ...     ...
41146         Burglary/B&E           Residence/Home   2023-06-06 02:58  DENTON
41147       Simple Assault           Residence/Home   2023-06-06 02:58  DENTON
41148            Vandalism  PARKING/DROP LOT/GARAGE   2023-06-06 08:24  DENTON
41149  Drug/Narc Violation  PARKING/DROP LOT/GARAGE   2023-06-06 09:53  DENTON
41150       Simple Assault           Residence/Home   2023-06-06 10:50  DENTON

[41151 rows x 4 columns]

In [ ]:
new_columns2 = ['Date_of_Occurrence', 'Offense_Description', 'Location_Type', 'City']
final_3 = final3[new_columns2]
final_3

      Date_of_Occurrence  Offense_Description            Location_Type    City
0       2019-11-06 00:00         Intimidation            Other/Unknown  DENTON
1       2019-11-06 00:00              Robbery  PARKING/DROP LOT/GARAGE  DENTON
2       2019-11-06 00:00          Shoplifting      GROCERY/SUPERMARKET  DENTON
3       2019-11-06 00:00   Swindle/Confidence               Cyberspace  DENTON
4       2019-11-06 00:01   All Other Offenses           Residence/Home  DENTON
...                  ...                  ...                      ...     ...
41146   2023-06-06 02:58         Burglary/B&E           Residence/Home  DENTON
41147   2023-06-06 02:58       Simple Assault           Residence/Home  DENTON
41148   2023-06-06 08:24            Vandalism  PARKING/DROP LOT/GARAGE  DENTON
41149   2023-06-06 09:53  Drug/Narc Violation  PARKING/DROP LOT/GARAGE  DENTON
41150   2023-06-06 10:50       Simple Assault           Residence/Home  DENTON

[41151 rows x 4 columns]

In [ ]:
updated1_fortworth

,Reported Date,Nature Of Call,From Date,Description,City,Division,Location Description,Location
0,10/22/2018,NARCOTIC VIOLATIONS,10/22/2018 06:15:00 PM,HSC 481.115(B) Poss CS PG 1 <1G 35A DRUG/NARCOTIC,FORT WORTH,NaN,13 HIGHWAY/ROAD/ALLEY,NaN
1,11/03/2020,HARASS,08/12/2020 05:18:00 AM,PC 42.07(C) Harassment,FORT WORTH,South,20 RESIDENCE/HOME,"(32.640426597727426, -97.33851074771222)"
2,02/20/2021,AUTO THEFT,02/20/2021 08:27:59 PM,PC 31.03(E)(4)(A)AUTO Theft>$1500<$20K (Auto t...,FORT WORTH,East,18 PARKING LOT/GARAGE,NaN
3,06/04/2019,NARCOTIC VIOLATIONS,06/04/2019 01:33:49 AM,HSC 481.117(B) Poss CS PG 3 <28G 35A DRUG/NARC...,NaN,NaN,13 HIGHWAY/ROAD/ALLEY,NaN
4,04/13/2019,DWI,04/13/2019 02:44:37 AM,PC 49.04 Driving While Intoxicated 90D DRIVING...,NaN,NaN,13 HIGHWAY/ROAD/ALLEY,NaN
...,...,...,...,...,...,...,...,...
315228,07/31/2008,CITY ORDIN,07/31/2008 04:44:00 PM,MISC CITY ORDINANCE Misc City Ordinances,FORT WORTH,NaN,13 HIGHWAY/ROAD/ALLEY,"(32.72940143032699, -97.22693857343134)"
315229,07/31/2008,AUTOTHEFT,07/31/2008 03:00:00 PM,PC 31.03 - AUTO Auto Theft,FORT WORTH,NaN,18 PARKING LOT/GARAGE,"(32.75998313976105, -97.17290554114979)"
315230,07/31/2008,HARASS,07/31/2008 04:00:00 PM,PC 42.07 Harassment,FORT WORTH,NaN,20 RESIDENCE/HOME,"(32.645514865010064, -97.32745649899542)"
315231,07/31/2008,THEFT,07/28/2008 09:00:00 PM,PC 31.03 - Others Theft - Others,FORT WORTH,NaN,20 RESIDENCE/HOME,"(32.76456153481421, -97.20437782869296)"
315232,07/31/2008,BURG VEHIC,07/27/2008 09:00:00 PM,PC 30.04 Burglary of Vehicle,FORT WORTH,NaN,NaN,NaN

In [ ]:
final4 = updated1_fortworth.rename(columns = {'From Date': 'Date_of_Occurrence', 'Location Description': 'Location_Type', 'Nature Of Call' : 'Offense_Description'})
final4

,Reported Date,Offense_Description,Date_of_Occurrence,Description,City,Division,Location_Type,Location
0,10/22/2018,NARCOTIC VIOLATIONS,10/22/2018 06:15:00 PM,HSC 481.115(B) Poss CS PG 1 <1G 35A DRUG/NARCOTIC,FORT WORTH,NaN,13 HIGHWAY/ROAD/ALLEY,NaN
1,11/03/2020,HARASS,08/12/2020 05:18:00 AM,PC 42.07(C) Harassment,FORT WORTH,South,20 RESIDENCE/HOME,"(32.640426597727426, -97.33851074771222)"
2,02/20/2021,AUTO THEFT,02/20/2021 08:27:59 PM,PC 31.03(E)(4)(A)AUTO Theft>$1500<$20K (Auto t...,FORT WORTH,East,18 PARKING LOT/GARAGE,NaN
3,06/04/2019,NARCOTIC VIOLATIONS,06/04/2019 01:33:49 AM,HSC 481.117(B) Poss CS PG 3 <28G 35A DRUG/NARC...,NaN,NaN,13 HIGHWAY/ROAD/ALLEY,NaN
4,04/13/2019,DWI,04/13/2019 02:44:37 AM,PC 49.04 Driving While Intoxicated 90D DRIVING...,NaN,NaN,13 HIGHWAY/ROAD/ALLEY,NaN
...,...,...,...,...,...,...,...,...
315228,07/31/2008,CITY ORDIN,07/31/2008 04:44:00 PM,MISC CITY ORDINANCE Misc City Ordinances,FORT WORTH,NaN,13 HIGHWAY/ROAD/ALLEY,"(32.72940143032699, -97.22693857343134)"
315229,07/31/2008,AUTOTHEFT,07/31/2008 03:00:00 PM,PC 31.03 - AUTO Auto Theft,FORT WORTH,NaN,18 PARKING LOT/GARAGE,"(32.75998313976105, -97.17290554114979)"
315230,07/31/2008,HARASS,07/31/2008 04:00:00 PM,PC 42.07 Harassment,FORT WORTH,NaN,20 RESIDENCE/HOME,"(32.645514865010064, -97.32745649899542)"
315231,07/31/2008,THEFT,07/28/2008 09:00:00 PM,PC 31.03 - Others Theft - Others,FORT WORTH,NaN,20 RESIDENCE/HOME,"(32.76456153481421, -97.20437782869296)"
315232,07/31/2008,BURG VEHIC,07/27/2008 09:00:00 PM,PC 30.04 Burglary of Vehicle,FORT WORTH,NaN,NaN,NaN

In [ ]:
drop_fortworth = final4.drop(columns = {"Reported Date", "Description", "Division", "Location"})
drop_fortworth

,Offense_Description,Date_of_Occurrence,City,Location_Type
0,NARCOTIC VIOLATIONS,10/22/2018 06:15:00 PM,FORT WORTH,13 HIGHWAY/ROAD/ALLEY
1,HARASS,08/12/2020 05:18:00 AM,FORT WORTH,20 RESIDENCE/HOME
2,AUTO THEFT,02/20/2021 08:27:59 PM,FORT WORTH,18 PARKING LOT/GARAGE
3,NARCOTIC VIOLATIONS,06/04/2019 01:33:49 AM,NaN,13 HIGHWAY/ROAD/ALLEY
4,DWI,04/13/2019 02:44:37 AM,NaN,13 HIGHWAY/ROAD/ALLEY
...,...,...,...,...
315228,CITY ORDIN,07/31/2008 04:44:00 PM,FORT WORTH,13 HIGHWAY/ROAD/ALLEY
315229,AUTOTHEFT,07/31/2008 03:00:00 PM,FORT WORTH,18 PARKING LOT/GARAGE
315230,HARASS,07/31/2008 04:00:00 PM,FORT WORTH,20 RESIDENCE/HOME
315231,THEFT,07/28/2008 09:00:00 PM,FORT WORTH,20 RESIDENCE/HOME
315232,BURG VEHIC,07/27/2008 09:00:00 PM,FORT WORTH,NaN

In [ ]:
new_columns3 = ['Date_of_Occurrence', 'Offense_Description', 'Location_Type', 'City']
final_4 = drop_fortworth[new_columns3]
final_4

,Date_of_Occurrence,Offense_Description,Location_Type,City
0,10/22/2018 06:15:00 PM,NARCOTIC VIOLATIONS,13 HIGHWAY/ROAD/ALLEY,FORT WORTH
1,08/12/2020 05:18:00 AM,HARASS,20 RESIDENCE/HOME,FORT WORTH
2,02/20/2021 08:27:59 PM,AUTO THEFT,18 PARKING LOT/GARAGE,FORT WORTH
3,06/04/2019 01:33:49 AM,NARCOTIC VIOLATIONS,13 HIGHWAY/ROAD/ALLEY,NaN
4,04/13/2019 02:44:37 AM,DWI,13 HIGHWAY/ROAD/ALLEY,NaN
...,...,...,...,...
315228,07/31/2008 04:44:00 PM,CITY ORDIN,13 HIGHWAY/ROAD/ALLEY,FORT WORTH
315229,07/31/2008 03:00:00 PM,AUTOTHEFT,18 PARKING LOT/GARAGE,FORT WORTH
315230,07/31/2008 04:00:00 PM,HARASS,20 RESIDENCE/HOME,FORT WORTH
315231,07/28/2008 09:00:00 PM,THEFT,20 RESIDENCE/HOME,FORT WORTH
315232,07/27/2008 09:00:00 PM,BURG VEHIC,NaN,FORT WORTH

In [ ]:
#resetting index
final_3.reset_index(drop=True, inplace=True)
final4.reset_index(drop=True, inplace=True)

In [ ]:
#merging all tables
complete = pd.concat([merge_austin_houston, final_3, final_4])
complete

,Date_of_Occurrence,Offense_Description,Location_Type,City
0,2022-01-01 00:00:00,Disorderly conduct,"Residence, Home (Includes Apartment)",HOUSTON
1,2022-01-01 00:00:00,Weapon law violations,"Residence, Home (Includes Apartment)",HOUSTON
2,2022-01-01 00:00:00,"Destruction, damage, vandalism","Highway, Road, Street, Alley",HOUSTON
3,2022-01-01 00:00:00,"Destruction, damage, vandalism","Residence, Home (Includes Apartment)",HOUSTON
4,2022-01-01 00:00:00,Weapon law violations,"Residence, Home (Includes Apartment)",HOUSTON
...,...,...,...,...
315228,07/31/2008 04:44:00 PM,CITY ORDIN,13 HIGHWAY/ROAD/ALLEY,FORT WORTH
315229,07/31/2008 03:00:00 PM,AUTOTHEFT,18 PARKING LOT/GARAGE,FORT WORTH
315230,07/31/2008 04:00:00 PM,HARASS,20 RESIDENCE/HOME,FORT WORTH
315231,07/28/2008 09:00:00 PM,THEFT,20 RESIDENCE/HOME,FORT WORTH
315232,07/27/2008 09:00:00 PM,BURG VEHIC,NaN,FORT WORTH

In [ ]:
#making contents of columns same format, all capitalized
complete['Offense_Description'] = complete['Offense_Description'].str.upper()

In [ ]:
complete['Location_Type'] = complete['Location_Type'].str.upper()

In [ ]:
complete = complete.rename(columns={'Date_of_Occurence': 'Date'})
complete

,Date_of_Occurrence,Offense_Description,Location_Type,City
1970-01-01 00:00:00.000000000,2022-01-01,DISORDERLY CONDUCT,"RESIDENCE, HOME (INCLUDES APARTMENT)",HOUSTON
1970-01-01 00:00:00.000000001,2022-01-01,WEAPON LAW VIOLATIONS,"RESIDENCE, HOME (INCLUDES APARTMENT)",HOUSTON
1970-01-01 00:00:00.000000002,2022-01-01,"DESTRUCTION, DAMAGE, VANDALISM","HIGHWAY, ROAD, STREET, ALLEY",HOUSTON
1970-01-01 00:00:00.000000003,2022-01-01,"DESTRUCTION, DAMAGE, VANDALISM","RESIDENCE, HOME (INCLUDES APARTMENT)",HOUSTON
1970-01-01 00:00:00.000000004,2022-01-01,WEAPON LAW VIOLATIONS,"RESIDENCE, HOME (INCLUDES APARTMENT)",HOUSTON
...,...,...,...,...
1970-01-01 00:00:00.000315228,2008-07-31,CITY ORDIN,13 HIGHWAY/ROAD/ALLEY,FORT WORTH
1970-01-01 00:00:00.000315229,2008-07-31,AUTOTHEFT,18 PARKING LOT/GARAGE,FORT WORTH
1970-01-01 00:00:00.000315230,2008-07-31,HARASS,20 RESIDENCE/HOME,FORT WORTH
1970-01-01 00:00:00.000315231,2008-07-28,THEFT,20 RESIDENCE/HOME,FORT WORTH
1970-01-01 00:00:00.000315232,2008-07-27,BURG VEHIC,NaN,FORT WORTH

In [ ]:
#converting date column from datetime to date
complete['Date_of_Occurrence'] = pd.to_datetime(complete['Date_of_Occurrence']).dt.date

In [ ]:
complete

,Date_of_Occurrence,Offense_Description,Location_Type,City
0,2022-01-01,DISORDERLY CONDUCT,"RESIDENCE, HOME (INCLUDES APARTMENT)",HOUSTON
1,2022-01-01,WEAPON LAW VIOLATIONS,"RESIDENCE, HOME (INCLUDES APARTMENT)",HOUSTON
2,2022-01-01,"DESTRUCTION, DAMAGE, VANDALISM","HIGHWAY, ROAD, STREET, ALLEY",HOUSTON
3,2022-01-01,"DESTRUCTION, DAMAGE, VANDALISM","RESIDENCE, HOME (INCLUDES APARTMENT)",HOUSTON
4,2022-01-01,WEAPON LAW VIOLATIONS,"RESIDENCE, HOME (INCLUDES APARTMENT)",HOUSTON
...,...,...,...,...
693921,2008-07-31,CITY ORDIN,13 HIGHWAY/ROAD/ALLEY,FORT WORTH
693922,2008-07-31,AUTOTHEFT,18 PARKING LOT/GARAGE,FORT WORTH
693923,2008-07-31,HARASS,20 RESIDENCE/HOME,FORT WORTH
693924,2008-07-28,THEFT,20 RESIDENCE/HOME,FORT WORTH
693925,2008-07-27,BURG VEHIC,NaN,FORT WORTH

In [ ]:
complete = complete.rename(columns={'Date_of_Occurrence': 'Date'})

In [ ]:
complete

,Date,Offense_Description,Location_Type,City
0,2022-01-01,DISORDERLY CONDUCT,"RESIDENCE, HOME (INCLUDES APARTMENT)",HOUSTON
1,2022-01-01,WEAPON LAW VIOLATIONS,"RESIDENCE, HOME (INCLUDES APARTMENT)",HOUSTON
2,2022-01-01,"DESTRUCTION, DAMAGE, VANDALISM","HIGHWAY, ROAD, STREET, ALLEY",HOUSTON
3,2022-01-01,"DESTRUCTION, DAMAGE, VANDALISM","RESIDENCE, HOME (INCLUDES APARTMENT)",HOUSTON
4,2022-01-01,WEAPON LAW VIOLATIONS,"RESIDENCE, HOME (INCLUDES APARTMENT)",HOUSTON
...,...,...,...,...
693921,2008-07-31,CITY ORDIN,13 HIGHWAY/ROAD/ALLEY,FORT WORTH
693922,2008-07-31,AUTOTHEFT,18 PARKING LOT/GARAGE,FORT WORTH
693923,2008-07-31,HARASS,20 RESIDENCE/HOME,FORT WORTH
693924,2008-07-28,THEFT,20 RESIDENCE/HOME,FORT WORTH
693925,2008-07-27,BURG VEHIC,NaN,FORT WORTH

In [ ]:
#displaying each unique offense type
print(complete["Offense_Description"].unique())
print(type(complete["Offense_Description"].unique()))

['DISORDERLY CONDUCT' 'WEAPON LAW VIOLATIONS'
 'DESTRUCTION, DAMAGE, VANDALISM' 'BURGLARY, BREAKING AND ENTERING'
 'SIMPLE ASSAULT' 'DRIVING UNDER THE INFLUENCE' 'AGGRAVATED ASSAULT'
 'ALL OTHER OFFENSES' 'TRESPASS OF REAL PROPERTY' 'ROBBERY' 'DRUNKENNESS'
 'THEFT FROM MOTOR VEHICLE' 'THEFT OF MOTOR VEHICLE PARTS OR ACCESSORY'
 'ALL OTHER LARCENY' 'INTIMIDATION' 'FORCIBLE FONDLING'
 'MOTOR VEHICLE THEFT' 'GAMBLING EQUIPMENT VIOLATIONS'
 'COUNTERFEITING, FORGERY' 'IDENTIFY THEFT' 'CREDIT CARD, ATM FRAUD'
 'EXTORTION, BLACKMAIL' 'FORCIBLE RAPE' 'SEXUAL ASSAULT WITH AN OBJECT'
 'DRUG, NARCOTIC VIOLATIONS' 'SHOPLIFTING' 'MURDER, NON-NEGLIGENT'
 'THEFT FROM BUILDING' 'FALSE PRETENSES, SWINDLE'
 'PORNOGRAPHS, OBSCENE MATERIAL' 'EMBEZZLEMENT' 'WELFARE FRAUD'
 'DRUG EQUIPMENT VIOLATIONS' 'ANIMAL CRUELTY'
 'ASSISTING OR PROMOTING PROSTITUTION'
 'HUMAN TRAFFICKING/COMMERCIAL SEX ACT' 'KIDNAPPING, ABDUCTION'
 'FORCIBLE SODOMY' 'STOLEN PROPERTY OFFENSES' 'ARSON'
 'HACKING/COMPUTER INVASION' 'BRIBERY' 'PURSE-SNATCHING'
 'FROM COIN-OPERATED MACHINE OR DEVICE' 'PROSTITUTION' 'IMPERSONATION'
 'CURFEW, LOITERING, VAGRANCY VIOLATIONS' 'FAMILY OFFENSES, NO VIOLENCE'
 'POCKET-PICKING' 'LIQUOR LAW VIOLATIONS' 'WIRE FRAUD'
 'PURCHASING PROSTITUTION' 'BAD CHECKS' 'NEGLIGENT MANSLAUGHTER'
 'PROMOTING GAMBLING' 'BETTING/WAGERING'
 'HUMAN TRAFFICKING/INVOLUNTARY SERVITUDE' 'JUSTIFIABLE HOMICIDE'
 'PEEPING TOM' 'STATUTORY RAPE' 'DEPENDENT AND NEGLECTED CHILD' 'THEFT'
 'FAMILY DISTURBANCE' 'BURGLARY OF VEH-NO SUSPECT/FU'
 'THEFT CATALYTIC CONVERTER' 'BURGLARY OF VEHICLE'
 'BURGLARY OF SHED/DETACHED GARAGE/STORAGE UNIT' 'AUTO THEFT' 'DWI'
 'ASSAULT W/INJURY-FAM/DATE VIOL' 'ASSAULT BY THREAT FAM/DATING'
 'DISTURBANCE - OTHER' 'BURGLARY NON RESIDENCE' 'HARASSMENT'
 'ASSAULT BY CONTACT' 'ASSAULT WITH INJURY' 'BURGLARY OF RESIDENCE'
 'DOC DISCHARGE GUN - PUB PLACE' 'UNLAWFUL CARRYING WEAPON'
 'CRIMINAL MISCHIEF' 'DRIVING WHILE INTOX / FELONY'
 'CRIMINAL MISCHIEF-NO SUSPECT' 'ASSAULT BY THREAT' 'MAIL THEFT'
 'DATING DISTURBANCE' 'FAMILY DISTURBANCE/PARENTAL' 'IDENTITY THEFT'
 'ASSAULT BY CONTACT FAM/DATING' 'DEBIT CARD ABUSE'
 'AGG ASLT STRANGLE/SUFFOCATE' 'CRIMINAL TRESPASS'
 'FALSE REPORT TO PEACE OFFICER' 'DOC FIGHTING' 'THEFT OF BICYCLE'
 'WARRANT ARREST NON TRAFFIC' 'GRAFFITI' 'THEFT OF LICENSE PLATE'
 'THEFT BY SHOPLIFTING' 'AGG ASSAULT' 'POSS OF DRUG PARAPHERNALIA'
 'VIOL OF PROTECTIVE ORDER' 'POSSESSION OF MARIJUANA'
 'CRASH/FAIL STOP AND RENDER AID' 'AGG ROBBERY/DEADLY WEAPON'
 'POSS CONTROLLED SUB/NARCOTIC' 'DWI 2ND' 'THEFT OF TRAILER'
 'PURSE SNATCHING' 'DEADLY CONDUCT' 'FORCED SODOMY'
 'SEXUAL ASSAULT OF CHILD/OBJECT' 'AGG RAPE OF A CHILD'
 'AGG SEXUAL ASSAULT W OBJECT' 'ONLINE IMPERSONATION'
 'POSS OF PROHIBITED WEAPON' 'COUNTERFEITING'
 'AGG ASSAULT FAM/DATE VIOLENCE' 'EVADING VEHICLE' 'INDECENT EXPOSURE'
 'DAMAGE CITY PROP' 'ASSAULT OF PREGNANT WM-FAM/DAT'
 'FELONY ENHANCEMENT/ASSLT W/INJ' 'TERRORISTIC THREAT' 'THEFT FROM PERSON'
 'FRAUD - OTHER' 'DAMAGE CITY VEHICLE' 'FORGERY AND PASSING'
 'CRED CARD ABUSE - OTHER' 'BURGLARY OF COIN-OP MACHINE'
 'CHILD CUSTODY INTERFERE' 'RESISTING ARREST OR SEARCH'
 'ROBBERY BY ASSAULT' 'TERRORISTIC THREAT-FAM/DAT VIO' 'RETALIATION'
 'INJURY TO ELDERLY PERSON' 'ASSAULT ON PUBLIC SERVANT'
 'FAILURE TO REG AS SEX OFFENDER' 'RAPE' 'INDECENCY WITH A CHILD/CONTACT'
 'VIOL OF EMERG PROTECTIVE ORDER' 'ATT ARSON'
 'AIRPORT - CRIMINAL TRESPASS' 'HARASSMENT OF A PUBLIC SERVANT'
 'PROTECTIVE ORDER' 'FAILURE TO IDENTIFY' 'FORGERY - OTHER'
 'THEFT OF AUTO PARTS' 'POSS OF FIREARM BY FELON' 'BOMB THREAT'
 'THEFT FROM AUTO' 'INJ TO ELDERLY   FAM/DATE VIOL'
 'OBTAIN CONTROLLED SUB BY FRAUD' 'STATUTORY RAPE OF CHILD'
 'AGG ASLT W/MOTOR VEH FAM/DAT V' 'ROBBERY BY THREAT'
 'DWI  .15 BAC OR ABOVE' 'JUSTIFIED HOMICIDE' 'DEL CONTROLLED SUB/OTHER'
 'INJURY TO CHILD' 'THEFT OF SERVICE' 'BREACH OF COMPUTER SECURITY'
 'INDECENT ASSAULT' 'RAPE OF A CHILD' 'SEXUAL ASSAULT W/ OBJECT'
 'CRIMINAL TRESPASS/TRANSIENT' 'VIOL CITY ORDINANCE - WRECKER'
 'UNLAWFUL RESTRAINT FAM/DAT VIO' 'FALSE ALARM OR REPORT' 'EVADING / FOOT'
 'BURG OF RES - FAM/DATING ASLT' 'AIRPORT PLACES WEAPON PROHIBIT'
 'RECKLESS DAMAGE' 'THEFT-NO SUSPECT/FOLLOWUP' 'POSS CONTROLLED SUB/OTHER'
 'CRUELTY TO ANIMALS' 'AGG ASSAULT WITH MOTOR VEH'
 'INTER EMERG PHONECALL FAM/DATE' 'AIRPORT - FEDERAL VIOL' 'MURDER'
 'DOC EXPOSURE' 'UCW LICENSE PREMISE' 'SEXUAL COERCION'
 'DOC DISPLAY GUN/DEADLY PUB PLC' 'DOC DISCHARGE GUN - PUB ROAD'
 'CRIMINAL TRESPASS/IN VEHICLE' 'FAIL TO REGISTER- MINOR VIC'
 'URINATING IN PUBLIC PLACE' 'CIVIL DISTURBANCE/DEMO' 'THEFT OF METAL'
 'INDECENCY WITH CHILD/EXPOSURE' 'FORCED SODOMY OF CHILD'
 'CONT SEX ABUSE OF CHILD' 'INTERFERING W/EMERG PHONE CALL'
 'SEXTING/TRANSMIT SEXUAL PHOTOS' 'VIOL OF BOND CONDITIONS'
 'AGG KIDNAPPING' 'ASSAULT ON PEACE OFFICER' 'THEFT BY EMBEZZLEMENT'
 'DEL CONTROLLED SUB/NARCOTIC' 'POSS/PROMO CHILD PORNOGRAPHY' 'LITTERING'
 'AGG ROBBERY BY ASSAULT' 'INJURY DISABLED INDIVIDUAL' 'KIDNAPPING'
 'VIOL STATE LAW - OTHER' 'EXPLOSIVE ORDNANCE DISPOSAL'
 'FRAUD FILING FINANCE STATEMENT' 'DWI - CHILD PASSENGER'
 'INVASIVE VISUAL RECORDING' 'POSS OF ALCOHOL - AGE 17 TO 20'
 'FALSE STATEMENT -OBTAIN CREDIT' 'CRASH/INTOXICATION ASSAULT'
 'ASSAULT  CONTACT-SEXUAL NATURE' 'CHILD ENDANGERMENT- ABANDONMEN'
 'DISCLOSE/PROMO INTIMATE VISUAL' 'TERRORISTIC THREAT-MASS CASLTY'
 'DOC ABUSE OR THREAT' 'CRIMINAL TRESPASS/HOTEL' 'HARBORING RUNAWAY CHILD'
 'EVADING / VEHICLE PURSUIT' 'UNLAWFUL RESTRAINT'
 'VIOL OF CAMPING ORDINANCE' 'AGG ASSAULT ON PEACE OFFICER'
 'ATTACK BY DOG' 'DWI - DRUG RECOGNITION EXPERT' 'CAPITAL MURDER'
 'VIOL CITY ORDINANCE - OTHER' 'VIOL TEMP EX PARTE  ORDER'
 'BURG OF RES - SEXUAL NATURE' 'RENTAL CAR/FAIL TO RETURN'
 'ONLINE SOLICITATION OF A MINOR' 'SMUGGLING ILLEGAL ALIEN'
 'HINDER SECURED CREDITORS' 'TAMPERING WITH CONSUMER PROD'
 'POCKET PICKING' 'TAMPERING WITH GOV RECORD' 'ATT THEFT' 'STALKING'
 'FALSE CALLER ID DISPLAY/SPOOF' 'ENTICING A CHILD' 'AGG RAPE'
 'FORGERY OF IDENTIFICATION' 'AGG ASSAULT ON PUBLIC SERVANT'
 'AGG ASLT ENHANC STRANGL/SUFFOC' 'PUBLIC LEWDNESS'
 'CRIMINAL SOLICITATION OF MINOR' 'PAROLE VIOL' 'UNLAWFUL INTERCEPTION'
 'AGG FORCED SODOMY OF CHILD' 'VIOL CITY ORDINANCE - SOUND'
 'VIOL CITY ORDINANCE - BOOTING' 'TAMPERING WITH EVIDENCE'
 'PROBATION VIOL' 'DEL CONTROLLED SUB/SYN NARC' 'NUISANCE ABATEMENT'
 'THEFT OF HEAVY EQUIPMENT' 'ATT BURGLARY NON RESIDENCE'
 'DEADLY CONDUCT FAM/DATE VIOL' 'MONEY LAUNDERING' 'ABUSE OF 911'
 'EXPLOITATION OF CHILD/ELDERLY' 'ARSON-CRIMINAL MISCHIEF'
 'MISREP AGE BY MINOR' 'HARASSMENT ONLINE' 'THEFT BY EXTORTION'
 'ATT BURGLARY OF RESIDENCE' 'FORGERY- CERTIFICATE OF TITLE'
 'AGG SEXUAL ASSAULT CHILD/OBJEC' 'FORGERY BY MAKING'
 'THEFT BY FALSE PRETEXT/BUNCO' 'DUI - AGE 17 TO 20'
 'INTERFERE W PO SERVICE ANIMALS' 'POSS DANG DRUG'
 'INTERFERENCE PUBLIC DUTIES' 'INJ TO DISABLED  FAM/DATE VIOL'
 'DUI - AGE 16 AND UNDER' 'CRASH/CRIM NEG HOMICIDE'
 'CRED CARD ABUSE BY FORGERY' 'HINDERING APPREHENSION'
 'CUSTODY ARREST TRAFFIC WARR' 'FORGERY BY ALTERATION' 'PROWLER'
 'OBTAIN DANG DRUG BY FRAUD' 'DOC UNREASONABLE NOISE'
 'DOMESTIC VIOLENCE/ALARM' 'DOC OFFENSIVE GESTURE'
 'BOMB THREAT - AIRCRAFT' 'RECKLESS CONDUCT' 'SEXTING DEPICTING A MINOR'
 'FRAUD-CARD SKIMMER' 'IMPERSONATING PUBLIC SERVANT'
 'VOCO - ALCOHOL  CONSUMPTION' 'FEDERAL VIOL/OTHER'
 'THEFT- APPROPRIATE STOLEN PROP' 'DUMPING REFUSE NEAR HIGHWAY'
 'ASSAULT OF A PREGNANT WOMAN' 'CONTEMPT OF COURT'
 'VIOL CITY ORDINANCE - DOG' 'DOC ABUSIVE LANGUAGE' 'CRASH/MANSLAUGHTER'
 'VIOL CITY ORDINANCE - AIRPORT' 'IDENTITY THEFT-TAX RETURNS'
 'AGG SEXUAL ASSAULT CHILD/OBJECT-SUPER' 'TAMPERING WITH ID NUMBER'
 'INJ/CHILD FV (NO CARE/CUSTODY)' 'INJURY TO CHILD (CARE/CUSTODY)'
 'FAILURE TO REPORT CHILD ABUSE' 'INHALANT ABUSE' 'BANK KITING'
 'AIRPORT - BREACH OF SECURITY' 'UNLAWFUL CARRY-LIC HOLDER'
 'SERIOUS INJURY TO A CHILD' 'POSS CRIMINAL INSTRUMENT'
 'POSS CONTROLLED SUB/SYN NARC' 'AGG KIDNAPPING FAM VIO'
 'TAKE WEAPON FRM POLICE OFFICER' 'DEL MARIJUANA'
 'DISRUPTIVE ACTS AT SCHOOLS' 'TAMPERING WITH WITNESS'
 'ENGAGING IN ORGANIZED CRIME' 'DEL OF ALCOHOL TO MINOR'
 'INJURY TO ELDERLY PERSON - SBI' 'CRASH/INTOX MANSLAUGHTER'
 'ESCAPE FROM CUSTODY' 'LIQUOR LAW VIOLATION/OTHER'
 'KEEPING GAMBLING PLACE' 'VIOL STAY AWAY ORDER'
 'SECURING EXEC-DOC BY DECEPTION' 'VIOL CITY ORDINANCE -FIREWORK'
 'APPLIC TO REVOKE PROBATION' 'SALE OF LIQ WITHOUT PERMIT'
 'AGG FORCED SODOMY' 'WEAPON VIOL - OTHER'
 'ILLUMIN AIRCRAFT INTENSE LIGHT' 'TOBACCO VIOL - UNDER AGE 21'
 'FICTITIOUS NAME' 'DISPOSAL OF SOLID WASTE' 'MANF CONTROLLED SUB - OTHER'
 'TRAFFICKING OF PERSONS' 'POSS SYNTHETIC MARIJUANA'
 'AGG PROMOTION OF PROSTITUTION' 'SALE OR PURCHASE OF CHILD'
 'FRAUD DESTRUCTION OF A WRITING' 'MISAPPLY FIDUCIARY PROP'
 'STAY AWAY ORDER' 'ATT AUTO THEFT' 'VIOL CITY ORDINANCE - CURFEW'
 'FIREARMS ON SCHOOL PROP' 'VIOL CITY ORDINANCE - TITLE 10'
 'CRIMES AGAINST ELDERLY' 'POSS OF ALCOHOL-AGE 16 & UNDER'
 'ABUSE OF OFFICIAL CAPACITY' 'FALSE REPORT TO CPS' 'PERJURY'
 'SWINDLE/CONFIDENCE' 'OTHER LARCENY' 'BURGLARY/B&E' 'DRUG/NARC VIOLATION'
 'THEFT FROM VEH' 'CREDIT/ATM FRAUD' 'THEFT FROM BLDG' 'VANDALISM'
 'COUNTERFEIT/FORGERY' 'DRUG EQUIP VIOLATION' 'IMPERSONATION FRAUD'
 'NEGL MANSLAUGHTER' 'PORNO/OBSCENE MATL' 'DRIVE UNDER INFL' 'RUNAWAY'
 'THEFT OF VEH PARTS' 'WEAPON LAW VIOLATION' 'THEFT FROM VENDING'
 'TRESPASSING' 'LIQUOR LAW VIOLATION' 'NONVIOL FAMILY OFF'
 'MURDER/NONNEG MANS' 'SEX ASSLT W/ OBJECT' 'STOLEN PROP OFFENSES'
 'KIDNAPPING/ABDUCTION' 'ASST/PROM PROS.' 'GAM EQUIP VIOLATIONS'
 'OP/PRO/ASST GAMBLING' 'INCEST' 'HUMAN TRAFFICKING/COMMERCIAL SEX ACTS'
 'EXTORTION/BLACKMAIL' 'NARCOTIC VIOLATIONS' 'HARASS' 'ASSAULT'
 'TRAFFIC CODE' 'AG ASSAULT' 'FRAUD' 'PENAL CODE' 'BURGLARY COMMERCIAL'
 'ROBBERY PERSON' 'BURGLARY VEHICLE' 'ASSAULT C' 'MISSING VEHICLE'
 'BURGLARY VEHICLE COMMERCI' 'PUBLIC INTOXICATION' 'SEX REGISTRATION'
 'BURGLARY RESIDENTIAL' 'CITY ORDINANCES' 'BURGLARY COIN' 'CITY ORDIN'
 'CRIM MISCH' 'VIOLATION PROTECTIVE ORDE' 'ROBBERY BUSINESS' 'FAMILY'
 'THEFTRECYC' 'BURG RES' 'ROBBERY CAR JACKING' 'THEFT RECYCLE' 'DUMPING'
 'PORNOGRAPHY' 'BURG VEHIC' 'WARRANT' 'ROBBERY INVASION' 'WEAPONS'
 'STOLEN VEHICLE' 'SEXUAL ASSAULT' 'ASSAULT ELDERLY'
 'UNLAWFUL DISCLOSURE OR PR' 'ROB BUSIN' 'THEFT TRAILER NONCOMMERCI' '00'
 'ROB PERS' 'HIT AND RUN ACCIDENT' 'THEFT TRAILER' 'ASSAULT CHILD'
 'COMMERCIAL AUTO THEFT' 'POSSESSION STOLEN PROPERT' 'GAMBLING'
 'VANDALISM/GRAFFITI' 'TABC OFFENSES' 'NARC VIOL' 'CREDIT CARD ABUSE'
 'PORNOGRAP' 'ANIMAL' 'TOBACCO OFFENSE' 'CARGO THEFT'
 'BURGLARY OF A VEHICLE' 'AUTOTHEFT' 'ROB CAR JK' 'PENALCODE'
 'IDENTIFY (NON REPORTABLE)' 'THEFT PUBLIC UTILITIES'
 'INTOXICATION ASSAULT' 'PUBLICINTO' 'FALSE ALARM' 'HARASSAMENT'
 'BURG BUILD' 'DEADLY CONDUCT-SHOOTING' 'UUMV' '320000000000' 'OTHER'
 '210086129' 'CRIM TRESP' 'TRAF CODE' 'SEXASSAULT' 'RECVEHOTH' 'BURG COMM'
 'TABCOFFENS' 'PROSTITUT' 'INDECEXPOS' 'INFO ONLY' 'NONPENALCO'
 'INTOX ASLT' 'HITANDRUN' 'KIDNAP' 'BURG COIN' 'ASLTELDERL' 'CRIMTRESWA'
 'SEXASSAULC' 'VIOLPROTEC' 'ACCIDENT' 'CARGOTHEFT' 'NARC INFO'
 'COMMAUTOTH' 'ROBB INVAS' 'SEX REGIST' 'PD PULL' 'THEFTPUBUT' 'ASLTCHILD'
 'MISS VEH' 'POSSSTOLPR' 'TOBACCOOFF' 'THFTNONCOM' 'BURGVEHCOM'
 'THEFTTRAIL' 'HARASSING PHONE CALL' 'TRAFFIC VI' 'THEFT FROM VEHICLE'
 'FOUPROP' 'HIT AND RUN' 'DOMESTIC DISTURBANCE' 'DOGBITE' 'INJ PERSON'
 'MENTAL APP' 'JUV CURFEW' 'FATALACCID' '5201 QUAIL FEATHER DR'
 'RECYCLE (NON REPORTABLE)' 'MISS PERS' 'FORGERY' '67'
 'INJURY TO CHILD/ENDRANGER' 'DRUG PARAPHERNALIA'
 'NON REPORTABLE OFFENSE RE' '011720230954' 'HUMAN TRAFFICKING'
 'DISCHARGE/DISPLAY FIREARM' 'LOST PROP' 'REPOSSVEH' 'CHOOSEONE'
 'FAL ALARM' 'PCU INFO' 'DECEASEDPE' 'RECYC INFO' 'DECOR CALL' 'NO REPORT'
 'BURGLARY' 'INVESTIGAT' 'ID INFO' 'INTELCRIMI' 'GAMBL INFO' 'JUSTIFIHOM'
 'ROB BANK' 'HUMAN TRAF' 'DOMESTIC D' 'BURGLARY R' '31.03' '18930'
 'SUSPICIOUS PERSON' 'HSC 481.115(C) POSS CS PG' 'DISTURBANCE'
 'BURGLARY OF A MOTOR VEHIC' 'DISOREDERLY CONDUCT' 'A'
 'SCHOOL (NON REPORTABLE)' 'SHOOTING' '101673' 'WARRANTS' 'WARRANT ARREST'
 'PERSON WITH WEAPON' 'TRUANCY WARRANT' 'HARASSSMENT'
 'BURGLARY OF BUILDING' 'DISORDERLY CONDUCT LANGUA' 'NORTH'
 'DOMESTIC ASSAULT' 'SEXUAL ASSAULT CHILD' 'SOUTH'
 'ROBBERY FINANCIAL INSTITU' 'MAJOR ACCIDENT' 'NARCOTICS VIOLATION' 'N'
 'LARCENY' 'AGGRAVATED ROBBERY' 'HARRASSMENT' 'M' 'ASSULT BY CONTACT'
 'SOU' '54176' '190059271' 'PERSON WITH A WEAPON' '90061870' '190067375'
 '190782044' 'DOMESTIC' 'MANSLAUGHTER' 'CIMINAL MISCHIEF' 'BMV' 'EVADING'
 'DDDDDDDDDDD' 'PC 31.03' 'LOUD MUSIC' 'DISORDERRLY CONDUCT'
 'FALSE REPORT' 'MOTOR VEHICLE ACCIDENT' '190102235'
 'PC 31.03 - BUILDING THEFT' 'THEFT OF RECYCLING' 'GC 106.02' '200023422'
 'BUGLARY' 'SHOTS FIRED' 'BOAT ACCIDENT' '2000' 'ASSAULT FAMILY VIOLENCE'
 '200048442' 'PC 28.02(D)(2) ARSON HABI' '200739316' 'THET' 'THAFT'
 'MARIN' 'INTERFERENCE WITH CHILD C' 'UNLAWFUL ELECTRONIC TRANS'
 '200065221' '200068870' '200069473' 'HARRASMENT' 'HIT & RUN' '4322'
 'BURG' '38.14' '200086359' 'DOMESTIC VIOLENCE' 'TEHFT' '200093144'
 '200097741' 'ON SATURDAY, DECEMBER 19,' '200098251' '210020499'
 'DISORDELY CONDUCT' 'BURGLAY OF A VEHICLE' '210034495' 'ACCESSIOR'
 'PRISONER PICKUP' '5' '210054022' 'THFET' '210068175' '210071729'
 'FLOCK ACTIVATION' '12203' 'DOMESTICE DISTURBANCE' '210083116'
 'LOCAL WARRANT' 'PANHANDLING' '210088798' 'NATURAL RESOURCE CODE 85.'
 '213' '210102480' 'ASSUALT' 'LOST CELL PHONES' '01/04' 'WRONG WAY DRIVER'
 'EVADING DETENTION VEHICLE' '220020056' '43' 'INVESTIGATION' '220047360'
 'FAMILY VIOLENCE' 'ASSAULT ON A PUBLIC SERVA' '220051180'
 'CRIMINAL MISCHIEF VEHICLE' 'CRIMINIAL MISCHIEF' 'UNAUTHORIZED'
 'CRIMINA MISCHIEF VEHICLE' 'DOMESTIC VIOLENCE / STRAN' '4416'
 'UNAUTHORIZED USE OF A VEH' 'TRES' 'ATTEMPT CRIMINAL TRESPASS' '9/26/22'
 'PC 29.03 AGG ROBBERY' 'EVADING ARREST' '3616'
 'LEAVING THE SCENE OF AN A' '2201010502' 'LOST PROPERTY' 'FAM ASS' 'THRE'
 'ONLINE HARASSMENT' '.' 'UNAUTHORIZED USE OF MOTOR'
 'SHOPLIFTING (NO SUSPECT I']
<class 'numpy.ndarray'>